bitstream = "abbabababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaaaaaababbbbbbababababaababbababbabababbababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababbabababababababbababaabababaabbabababbabababababbababababababaaaaababbbbbbababababaabababababababaabababbababababababaaaaababbbbbbababababaababababababababbababaabababaaaaaababbbbbbababababaababbababbabababbababbbbbbababababaababababababababbababaabababaabbabababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaaaaaababbbbbbababababaababbababbabababababababaababbababbabababbababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababbabababababababbababaabababaabbabababbabbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaaaaaababbbbbbababababaababbababbabababbababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababbabababababababbababaabababaabbabababbababa"

count_a = 0
count_b = 0
for char in bitstream:
	if char == 'a':
		count_a += 1
	elif char == 'b':
		count_b += 1

print(f"Number of 'a': {count_a}")
print(f"Number of 'b': {count_b}")